"""
Per-fraud-type recall, pooled across generator seeds.

One test slice holds only a few dozen events of each fraud type, so a per-type
recall from a single run has a binomial interval tens of points wide. Reading a
low number there as "the detector is weak on MULE" mistakes sampling noise for a
finding — the same trap the capability ablation fell into.

This pools the held-out slices of many seeds and reports each rate with a Wilson
interval, so the types can actually be compared.

  python recall_by_type.py              resume until every seed is trained
  python recall_by_type.py --report     print results, run nothing

Reuses the datasets generated by ablation_seeds.py; missing ones are generated.
Resumable and time-budgeted, like ablation_seeds.py. Nothing in models/ is
touched — training goes to a scratch directory.

Results are design targets on synthetic data, not validated findings.
"""

import argparse
import json
import math
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
GEN_DIR = os.path.join(ROOT, "data-generator")
STATE = os.path.join(HERE, "models", "ablation", "recall_by_type.json")
SCRATCH = "/tmp/ablation_seeds"

DEFAULT_SEEDS = (42, 7, 13, 99, 2026, 1, 2, 3, 5, 8,
                 11, 17, 23, 31, 44, 58, 77, 101, 123, 777)


def _dataset(seed):
    out = os.path.join(SCRATCH, f"seed{seed}")
    csv = os.path.join(out, "transactions.csv")
    if os.path.exists(csv):
        return csv
    os.makedirs(out, exist_ok=True)
    proc = subprocess.run(
        [sys.executable, "generator.py", "--seed", str(seed), "--out", out],
        cwd=GEN_DIR, capture_output=True, text=True)
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout[-1500:] + proc.stderr[-1500:])
        raise SystemExit(f"generation failed for seed={seed}")
    return csv


def _train(csv):
    models = os.path.join(SCRATCH, "models_recall")
    os.makedirs(models, exist_ok=True)
    env = dict(os.environ, DATASET_CSV=csv, MODELS_DIR=models)
    proc = subprocess.run([sys.executable, os.path.join(HERE, "train.py")],
                          cwd=HERE, env=env, capture_output=True, text=True)
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout[-1500:] + proc.stderr[-1500:])
        raise SystemExit("training failed")
    with open(os.path.join(models, "metrics.json")) as fh:
        return json.load(fh)["by_fraud_type"]


def _load():
    if os.path.exists(STATE):
        with open(STATE) as fh:
            return json.load(fh)
    return {}


def _save(state):
    os.makedirs(os.path.dirname(STATE), exist_ok=True)
    with open(STATE, "w") as fh:
        json.dump(state, fh, indent=2)


def wilson(caught, n, z=1.96):
    """Wilson score interval — well-behaved at small n and rates near 0 or 1,
    unlike the normal approximation, which is exactly the regime here."""
    if n == 0:
        return 0.0, 0.0, 0.0
    p = caught / n
    denom = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / denom
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / denom
    return p, max(0.0, centre - half), min(1.0, centre + half)


def run(seeds, budget):
    state = _load()
    deadline = time.time() + budget
    todo = [s for s in seeds if str(s) not in state]
    if not todo:
        return state, True
    print(f"{len(todo)} seed(s) left")
    for seed in todo:
        if time.time() >= deadline:
            left = len([s for s in seeds if str(s) not in state])
            print(f"\nbudget reached — {left} seed(s) left; invoke again.")
            return state, False
        print(f"  seed={seed}", flush=True)
        state[str(seed)] = _train(_dataset(seed))
        _save(state)
    return state, True


def report(state):
    if not state:
        print("no results yet.")
        return
    types = sorted({t for v in state.values() for t in v})
    print(f"\npooled over {len(state)} seeds "
          f"({', '.join(sorted(state, key=int))})\n")
    print(f"{'fraud type':<14}{'caught':>8}{'events':>8}{'recall':>9}"
          f"{'95% CI (Wilson)':>22}")
    rows = []
    for t in types:
        caught = sum(v[t]["caught"] for v in state.values() if t in v)
        n = sum(v[t]["n"] for v in state.values() if t in v)
        p, lo, hi = wilson(caught, n)
        rows.append((t, caught, n, p, lo, hi))
        print(f"{t:<14}{caught:>8}{n:>8}{p:>9.1%}"
              f"{f'[{lo:.1%}, {hi:.1%}]':>22}")

    print("\nsingle-seed comparison (what one run would have told you):")
    one = state[sorted(state, key=int)[0]]
    for t in types:
        if t in one:
            p, lo, hi = wilson(one[t]["caught"], one[t]["n"])
            print(f"  {t:<12}{p:>7.1%}  (n={one[t]['n']:<4}) "
                  f"CI [{lo:.1%}, {hi:.1%}]")

    # Which gaps survive pooling: non-overlapping intervals only.
    print("\ntypes whose intervals do not overlap the best type's:")
    best = max(rows, key=lambda r: r[3])
    for t, caught, n, p, lo, hi in rows:
        if t == best[0]:
            continue
        print(f"  {t:<12} {'yes — genuinely weaker' if hi < best[4] else 'no'}")
    print(f"\n(best: {best[0]} at {best[3]:.1%})")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seeds", default=",".join(str(s) for s in DEFAULT_SEEDS))
    ap.add_argument("--budget", type=float, default=35.0)
    ap.add_argument("--report", action="store_true")
    args = ap.parse_args()

    if args.report:
        report(_load())
        return
    state, done = run([int(s) for s in args.seeds.split(",")], args.budget)
    if done:
        report(state)


if __name__ == "__main__":
    main()
